favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0
  lightness: 0.7240143
  brandStrength: 0.7210931330919266
  brandColors:
    - '#02011F'
    - '#284178'
    - '#FAFACF'
    - '#64809A'
    - '#A2775C'
  rhythmicContrast: 0.01971326
typography_spectrum: 0.05247225356288254
layout_spectrum: 0.8978494
cta:
  bucket: null
  version: null
  domain: null
name: Pallados
