name: Pallados
favicon: null
layout_spectrum: 0.7777778
typography_spectrum: 0.3010753
title: Pallados Consulting
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ccbfac'
    - '#60a845'
    - '#e4dfd2'
    - '#94c280'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 1
purpose: []
